import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div>
        <nav>
        <ul>
          <li>
          <Link href={"/"}>Home</Link>
          </li>
          <li>
          <Link href={"/todo"}>Todo</Link>
          </li>
          <li>
          <Link href={"/task"}>Task</Link>
          </li>
        </ul>
      </nav>
      {children}
        </div>
       </body>
    </html>
  )
}
